// Code generated by mockery v2.1.0. DO NOT EDIT.

package kubectlmock

import (
	exec "os/exec"

	mock "github.com/stretchr/testify/mock"
)

// CmdRunner is an autogenerated mock type for the CmdRunner type
type CmdRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0
func (_m *CmdRunner) Run(_a0 *exec.Cmd) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*exec.Cmd) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
