// Code generated by mockery (devel). DO NOT EDIT.

package kubectlmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/slok/kahoy/internal/model"
)

// K8sObjectDecoder is an autogenerated mock type for the K8sObjectDecoder type
type K8sObjectDecoder struct {
	mock.Mock
}

// DecodeObjects provides a mock function with given fields: ctx, raw
func (_m *K8sObjectDecoder) DecodeObjects(ctx context.Context, raw []byte) ([]model.K8sObject, error) {
	ret := _m.Called(ctx, raw)

	var r0 []model.K8sObject
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []model.K8sObject); ok {
		r0 = rf(ctx, raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.K8sObject)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, raw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
