// Code generated by mockery (devel). DO NOT EDIT.

package modelmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KubernetesDiscoveryClient is an autogenerated mock type for the KubernetesDiscoveryClient type
type KubernetesDiscoveryClient struct {
	mock.Mock
}

// GetServerGroupsAndResources provides a mock function with given fields: ctx
func (_m *KubernetesDiscoveryClient) GetServerGroupsAndResources(ctx context.Context) ([]*v1.APIGroup, []*v1.APIResourceList, error) {
	ret := _m.Called(ctx)

	var r0 []*v1.APIGroup
	if rf, ok := ret.Get(0).(func(context.Context) []*v1.APIGroup); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.APIGroup)
		}
	}

	var r1 []*v1.APIResourceList
	if rf, ok := ret.Get(1).(func(context.Context) []*v1.APIResourceList); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*v1.APIResourceList)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
