// Code generated by mockery (devel). DO NOT EDIT.

package managemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/slok/kahoy/internal/model"
)

// ResourceManager is an autogenerated mock type for the ResourceManager type
type ResourceManager struct {
	mock.Mock
}

// Apply provides a mock function with given fields: ctx, resources
func (_m *ResourceManager) Apply(ctx context.Context, resources []model.Resource) error {
	ret := _m.Called(ctx, resources)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Resource) error); ok {
		r0 = rf(ctx, resources)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, resources
func (_m *ResourceManager) Delete(ctx context.Context, resources []model.Resource) error {
	ret := _m.Called(ctx, resources)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Resource) error); ok {
		r0 = rf(ctx, resources)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
