// Code generated by mockery (devel). DO NOT EDIT.

package processmock

import (
	context "context"

	model "github.com/slok/kahoy/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ResourceProcessor is an autogenerated mock type for the ResourceProcessor type
type ResourceProcessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: ctx, resources
func (_m *ResourceProcessor) Process(ctx context.Context, resources []model.Resource) ([]model.Resource, error) {
	ret := _m.Called(ctx, resources)

	var r0 []model.Resource
	if rf, ok := ret.Get(0).(func(context.Context, []model.Resource) []model.Resource); ok {
		r0 = rf(ctx, resources)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Resource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []model.Resource) error); ok {
		r1 = rf(ctx, resources)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
